env:
  browser: true
  es2021: true
extends:
  - airbnb-base
  - prettier
parser: '@typescript-eslint/parser'
parserOptions:
  ecmaVersion: latest
  sourceType: module
plugins:
  - '@typescript-eslint'
  - 'prettier'
rules:
  {
    'prettier/prettier': 'error',
    import/extensions: [error, ignorePackages, { js: never, jsx: never, ts: never, tsx: never }],
    no-console: 'off',
    no-shadow: 'off',
    no-unused-vars: 'off',
    '@typescript-eslint/no-unused-vars': ['error'],
    lines-between-class-members: ['error', 'always', { 'exceptAfterSingleLine': true }]
  }
settings:
  import/resolver:
    node:
      extensions: ['.js', '.ts']
